services:
  web:
    build: .
    env_file:
      - ./.env
    environment:
      db_user: ${POSTGRES_USER:-fad_db_user}
      db_pass: ${POSTGRES_PASSWORD-fad_db_pass}
      db_server_ip: pg
      db_port: ${POSTGRES_PORT:-5432}
    ports:
      - ${WEB_PORT:-80}:5000
    depends_on:
      - pg
    
  pg:
    image: postgres:${POSTGRES_VERSION:-17.6}
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: "os_commands"
      POSTGRES_USER: ${POSTGRES_USER:-fad_db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fad_db_pass}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ${POSTGRES_DBDATA_DIR:-/opt/fad/db/}:/var/lib/postgresql/data
      - ./db_scripts/:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
      
