version: '3'
services:
  web:
    build: .
    env_file:
      - ./.env
    environment:
      db_user: ${POSTGRES_USER}
      db_pass: ${POSTGRES_PASSWORD}
      db_server_ip: ${POSTGRES_IP}
      db_port: ${POSTGRES_PORT}
    ports:
      - 80:5000
    depends_on:
      - pg
    
  pg:
    image: postgres:13.3
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: "os_commands"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - /opt/flask-app/db/pgdata/:/var/lib/postgresql/data
      - ./db_scripts/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
      
